# Generated by Django 5.2.10 on 2026-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_serviceablelocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="health_categories/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
