# Generated by Django 5.2.10 on 2026-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_healthcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="health_categories/"
            ),
        ),
    ]
